### PR TITLE
Prepare AppLovin adapters for release - 5.1.0.0

### PR DESCRIPTION
**Pull request by chauduyphanvu1**

### CODE REVIEW

**Comment by pangia** [comment]
Getting error with new version -->  'undeclared identifier 'ALPrivacySettings' in custom event files.

screen shot 2018-08-13 at 4 08 09 pm

**Comment by chauduyphanvu1** [comment]
@pangia - ensure that you are using the latest version of the AppLovin adapters. We fixed this in https://github.com/mopub/mopub-ios-mediation/commit/cc08e678fa889c884b2dc35cd1101d107abc535c#diff-672c534b6c7c5101d4397bc3a3453b78.

**Comment by pangia** [comment]
We just downloaded them.

**Comment by chauduyphanvu1** [comment]
@pangia - do you still see the issue? How did you integrate the adapters (binaries drag-and-drop or CocoaPods)? I recommend opening an issue on the issue tracker to have us look into it (comments on PRs are not monitored).

**Pull request merged**
